### ISSUE TITLE
Not pulling all Asana Project?

### ISSUE THREAD

**Issue by invinciberry** [lacherogwu/alfred-workflows-asana-automation#1]
Some projects that I have access to are not showing up when using -p to create a task. I tried to use the Asana command and update projects, but still missing them.

**Comment by lacherogwu** [comment]
Did you try to resync the data? Using the asana keyword and then select the sync projects list

**Comment by invinciberry** [comment]
Thanks for the quick reply, yes I did, I tried all 3 resyncing projects, sections and users. Please lmk if you need more info.

**Comment by lacherogwu** [comment]
When you selecting sync projects, do you get a successful message?
like 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/49835614/159766901-05771b67-1c46-4019-8518-cd8f16cd4047.png">

Try to right-click on the automation in Alfred workflow → Open in Finder, search for a file called "projects.json" and share with me this file, and then remove it.

and then run again the command "task some title -p" and let me know if that fixed the issue.

My pleasure to help :)

**Comment by invinciberry** [comment]
I just ran the sync project command again, and it does say projects synced successfully.
![Screen Shot 2022-03-24 at 09 22 53](https://user-images.githubusercontent.com/30306206/159925799-6aca6fed-b420-4e14-a62f-a0852bf50d8a.png)

And I looked in the projects.json file, and it does not contain those missing projects. After deleting it and trying the task command again, the previously missing project is still missing. The workflow pulled an identical projects.json file into the workflow folder.

**Comment by lacherogwu** [comment]
Can you tell me how menu objects are in the projects.json?
If not, just send me that file and I'll check.

**Comment by invinciberry** [comment]
50. feels like a coded limit? (Sorry I am crazy with over 80 projects 😂

**Comment by lacherogwu** [comment]
Yeah it's probably the case here :)
I'll push an update shortly

**Comment by invinciberry** [comment]
Thank you so much! I know this is more of a feature request, is it possible to add a default due date or assign a due date through this workflow?

**Comment by lacherogwu** [comment]
I'll be honest with you :) I wrote this code a long time ago and I'm not using Asana anymore, so I won't do any maintenance or add more features, but the bug you mentioned is very simple to fix so it's not a problem :)

**Comment by lacherogwu** [comment]
I've pushed the new code, please download the new alfred workflow, v3.2.2

Enjoy!

**Comment by invinciberry** [comment]
Odd, I just tested the new version by reinstalling the workflow. Still now pulling more than 50 projects tho.

**Comment by lacherogwu** [comment]
Are you sure you are using V3.2.2?
Can you send me a picture of what code you see in:
Alfred workflow → Open in Finder → projects.js

**Comment by invinciberry** [comment]
![Screen Shot 2022-03-24 at 11 25 27](https://user-images.githubusercontent.com/30306206/159951122-920404f5-43a8-4551-9277-d97ed63ab59c.png)

**Comment by invinciberry** [comment]
![Screen Shot 2022-03-24 at 11 25 59](https://user-images.githubusercontent.com/30306206/159951238-7a9be218-5532-4ded-a855-4420592024f7.png)

**Comment by invinciberry** [comment]
hummm, odd. This does look like v3.2. I manually updated the projects.js file to v3.2.2 and it works fine now!
