### ISSUE TITLE
Can't connect to get ID and workspace

### ISSUE THREAD

**Issue by miriamtocino** [lacherogwu/alfred-workflows-asana-automation#3]
Hi there - I just bought a new Mac and trying to install this workflow on my new machine. But it doesn't seem to work and it also doesn't give any error message.

Does anyone now how to troubleshoot this one? Thanks!

**Comment by lacherogwu** [comment]
Hi, I would recommend you to switch to Raycast instead of Alfred, and they have also Asana integration which works great
